version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: devops-prj-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devops-net

  backend:
    build:
      context: ./app/backend
    container_name: devops-prj-backend
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: todolist_db
      DB_DIALECT: mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: always
    networks:
      - devops-net
    
  frontend:
    build:
      context: ./app/frontend
    container_name: devops-prj-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - devops-net

networks:
  devops-net:

volumes:
  mysql_data:
