name: CI/CD DevOps Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to ACR
      run: |
        docker login ${{ secrets.ACR_LOGIN_SERVER }} \
          -u ${{ secrets.ACR_USERNAME }} \
          -p ${{ secrets.ACR_PASSWORD }}


    - name: Build backend image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/devops-prj-backend:latest ./app/backend

    - name: Build frontend image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/devops-prj-frontend:latest ./app/frontend

    - name: Push backend image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/devops-prj-backend:latest

    - name: Push frontend image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/devops-prj-frontend:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure kubeconfig for AKS
      run: |
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig

    - name: Deploy to AKS
      run: |
        kubectl --kubeconfig=./kubeconfig apply -f k8s/aks/
